Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    #config.vm.box = "carlosefr/centos-7"
    (1..3).each do |i|
      config.vm.define "worker#{i}" do |worker|
        worker.vm.network "private_network", ip: "192.168.60.11#{i}"
        worker.vm.hostname = "worker#{i}"
        worker.vm.provision "shell", inline: "swapoff -a"
        worker.vm.provider "virtualbox" do |v|
          v.memory = 1024
          v.cpus = 1
          end
        end
      end
    end